import React from 'react'
import { shallow, mount } from 'enzyme'
import { expect, assert } from 'chai'
import sinon from 'sinon'
import PhotoContainer, { mapStateToProps } from '../../src/containers/PhotoContainer'
